version: '2.0'

services:
  mysqldb:
    image: mysql:5.7
    container_name : mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome123
      - MYSQL_DATABASE=mahesh
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    networks:
      - test
  myapp-main:
    image: azurebackend
    container_name : hotelmanagement
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - 8081:8080
    networks:
      - test
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Welcome123
      - DATABASE_NAME=mahesh
      - DATABASE_PORT=3307
networks:
  test:
